# Generated by Django 5.2.9 on 2025-12-22 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(help_text='Type of sensor (defines table schema)', max_length=50)),
                ('table_name', models.CharField(help_text="PostgreSQL table name for this sensor's data", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional sensor configuration')),
                ('column_schema', models.JSONField(default=dict, help_text="Column definitions for the sensor's data table")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('reading_count', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='experiments.experiment')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this API key', max_length=100)),
                ('key_hash', models.CharField(help_text='SHA256 hash of the API key', max_length=64)),
                ('key_prefix', models.CharField(help_text='First 8 characters for identification', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
