# Generated by Django 5.2.9 on 2025-12-26 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedFieldError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='The computed field that failed', max_length=100)),
                ('error_type', models.CharField(help_text="Type of error (e.g., 'SyntaxError', 'TimeoutError')", max_length=100)),
                ('error_message', models.TextField(help_text='Full error message')),
                ('input_data', models.JSONField(help_text='The input data that caused the error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_field_errors', to='sensors.sensor')),
            ],
            options={
                'db_table': 'computed_field_errors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor', '-created_at'], name='computed_fi_sensor__f06b77_idx')],
            },
        ),
    ]
