apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: $__env{DB_NAME}
    user: $__env{DB_USER}
    secureJsonData:
      password: $__env{DB_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
